export const REDUX_SESSION_STORAGE = 'redux-session-storage'
export const REDUX_LOCAL_STORAGE_PREFIX = 'redux-local-storage'
export const RETRIEVE_STATE = 'RETRIEVE_STATE'
export const SESSION_STORAGE = 'sessionStorage'
export const LOCAL_STORAGE = 'localStorage'
export const GET_ITEM = 'getItem'
export const SET_ITEM = 'setItem'
export const REMOVE_ITEM = 'removeItem'
